-- Create user_pets table to track pet farming
CREATE TABLE public.user_pets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id TEXT NOT NULL,
  pet_type TEXT NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT user_pets_pkey PRIMARY KEY (id),
  CONSTRAINT user_pets_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
) TABLESPACE pg_default;

-- Create index on user_id for faster queries
CREATE INDEX idx_user_pets_user_id ON public.user_pets(user_id);
